// <auto-generated />
using System;
using MeatFlow.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MeatFlow.Data.Migrations
{
    [DbContext(typeof(MeatFlowDbContext))]
    partial class MeatFlowDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MeatFlow.Model.Entities.Carne", b =>
                {
                    b.Property<Guid>("IdtCarne")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("IDT_CARNE");

                    b.Property<DateTime>("DatAtualizacao")
                        .HasColumnType("datetime2")
                        .HasColumnName("dat_atualizacao");

                    b.Property<DateTime>("DatCriacao")
                        .HasColumnType("datetime2")
                        .HasColumnName("dat_criacao");

                    b.Property<string>("DescricaoCarne")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("descricao_carne");

                    b.Property<string>("OrigemCarne")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("origem_carne");

                    b.HasKey("IdtCarne");

                    b.ToTable("carne", (string)null);
                });

            modelBuilder.Entity("MeatFlow.Model.Entities.Cidade", b =>
                {
                    b.Property<Guid>("IdtCidade")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("IDT_CIDADE");

                    b.Property<DateTime>("DatAtualizacao")
                        .HasColumnType("datetime2")
                        .HasColumnName("dat_atualizacao");

                    b.Property<DateTime>("DatCriacao")
                        .HasColumnType("datetime2")
                        .HasColumnName("dat_criacao");

                    b.Property<Guid>("IdtEstado")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("IDT_ESTADO");

                    b.Property<string>("NomeCidade")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("nome_cidade");

                    b.HasKey("IdtCidade");

                    b.HasIndex("IdtEstado");

                    b.ToTable("cidade", (string)null);
                });

            modelBuilder.Entity("MeatFlow.Model.Entities.Comprador", b =>
                {
                    b.Property<Guid>("IdtComprador")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("IDT_COMPRADOR");

                    b.Property<DateTime>("DatAtualizacao")
                        .HasColumnType("datetime2")
                        .HasColumnName("dat_atualizacao");

                    b.Property<DateTime>("DatCriacao")
                        .HasColumnType("datetime2")
                        .HasColumnName("dat_criacao");

                    b.Property<string>("DocumentoFiscal")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("nvarchar(14)")
                        .HasColumnName("documento_fiscal");

                    b.Property<Guid>("IdtCidade")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("IDT_CIDADE");

                    b.Property<string>("NomeComprador")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("nome_comprador");

                    b.HasKey("IdtComprador");

                    b.HasIndex("DocumentoFiscal")
                        .IsUnique();

                    b.HasIndex("IdtCidade");

                    b.ToTable("comprador", (string)null);
                });

            modelBuilder.Entity("MeatFlow.Model.Entities.Estado", b =>
                {
                    b.Property<Guid>("IdtEstado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("IDT_ESTADO");

                    b.Property<DateTime>("DatAtualizacao")
                        .HasColumnType("datetime2")
                        .HasColumnName("dat_atualizacao");

                    b.Property<DateTime>("DatCriacao")
                        .HasColumnType("datetime2")
                        .HasColumnName("dat_criacao");

                    b.Property<string>("NomeEstado")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("nome_estado");

                    b.Property<string>("SiglaEstado")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)")
                        .HasColumnName("sigla_estado");

                    b.HasKey("IdtEstado");

                    b.HasIndex("SiglaEstado")
                        .IsUnique();

                    b.ToTable("estado", (string)null);
                });

            modelBuilder.Entity("MeatFlow.Model.Entities.ItemPedido", b =>
                {
                    b.Property<Guid>("IdtItemPedido")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("IDT_ITEM_PEDIDO");

                    b.Property<string>("CodigoMoeda")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)")
                        .HasColumnName("codigo_moeda");

                    b.Property<DateTime>("DatAtualizacao")
                        .HasColumnType("datetime2")
                        .HasColumnName("dat_atualizacao");

                    b.Property<DateTime>("DatCriacao")
                        .HasColumnType("datetime2")
                        .HasColumnName("dat_criacao");

                    b.Property<Guid>("IdtCarne")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("IDT_CARNE");

                    b.Property<Guid>("IdtPedido")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("IDT_PEDIDO");

                    b.Property<decimal>("QuantidadeKg")
                        .HasColumnType("decimal(10,3)")
                        .HasColumnName("quantidade_kg");

                    b.Property<decimal>("ValorUnitario")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("valor_unitario");

                    b.HasKey("IdtItemPedido");

                    b.HasIndex("IdtCarne");

                    b.HasIndex("IdtPedido");

                    b.ToTable("item_pedido", (string)null);
                });

            modelBuilder.Entity("MeatFlow.Model.Entities.Pedido", b =>
                {
                    b.Property<Guid>("IdtPedido")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("IDT_PEDIDO");

                    b.Property<DateTime>("DatAtualizacao")
                        .HasColumnType("datetime2")
                        .HasColumnName("dat_atualizacao");

                    b.Property<DateTime>("DatCriacao")
                        .HasColumnType("datetime2")
                        .HasColumnName("dat_criacao");

                    b.Property<DateTime>("DataPedido")
                        .HasColumnType("datetime2")
                        .HasColumnName("data_pedido");

                    b.Property<Guid>("IdtComprador")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("IDT_COMPRADOR");

                    b.HasKey("IdtPedido");

                    b.HasIndex("IdtComprador");

                    b.ToTable("pedido", (string)null);
                });

            modelBuilder.Entity("MeatFlow.Model.Entities.Cidade", b =>
                {
                    b.HasOne("MeatFlow.Model.Entities.Estado", "Estado")
                        .WithMany("Cidades")
                        .HasForeignKey("IdtEstado")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Estado");
                });

            modelBuilder.Entity("MeatFlow.Model.Entities.Comprador", b =>
                {
                    b.HasOne("MeatFlow.Model.Entities.Cidade", "Cidade")
                        .WithMany("Compradores")
                        .HasForeignKey("IdtCidade")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cidade");
                });

            modelBuilder.Entity("MeatFlow.Model.Entities.ItemPedido", b =>
                {
                    b.HasOne("MeatFlow.Model.Entities.Carne", "Carne")
                        .WithMany("ItensPedido")
                        .HasForeignKey("IdtCarne")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MeatFlow.Model.Entities.Pedido", "Pedido")
                        .WithMany("ItensPedido")
                        .HasForeignKey("IdtPedido")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Carne");

                    b.Navigation("Pedido");
                });

            modelBuilder.Entity("MeatFlow.Model.Entities.Pedido", b =>
                {
                    b.HasOne("MeatFlow.Model.Entities.Comprador", "Comprador")
                        .WithMany("Pedidos")
                        .HasForeignKey("IdtComprador")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Comprador");
                });

            modelBuilder.Entity("MeatFlow.Model.Entities.Carne", b =>
                {
                    b.Navigation("ItensPedido");
                });

            modelBuilder.Entity("MeatFlow.Model.Entities.Cidade", b =>
                {
                    b.Navigation("Compradores");
                });

            modelBuilder.Entity("MeatFlow.Model.Entities.Comprador", b =>
                {
                    b.Navigation("Pedidos");
                });

            modelBuilder.Entity("MeatFlow.Model.Entities.Estado", b =>
                {
                    b.Navigation("Cidades");
                });

            modelBuilder.Entity("MeatFlow.Model.Entities.Pedido", b =>
                {
                    b.Navigation("ItensPedido");
                });
#pragma warning restore 612, 618
        }
    }
}
